spring.application.name=eureka-registry-naming-server
spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.cloud.config.profile=dev
server.port=${eureka-registry-naming-server.uriport}
eureka.client.fetch-registry=${eureka-registry-naming-server.fetchregistry}

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
